### ISSUE TITLE
Sync message always gets denied when pulling

### ISSUE THREAD

**Issue by tok-kkk** [renproject/aw#59]
The `Gossiper.didReceivePush()` function will deny the content id in the filter after the context is done. https://github.com/renproject/aw/blob/27ccfc3bf6e42e58328bafc71802d139da40f6a3/peer/gossip.go#L104-L112

But the context is defer cancelled and will be cancelled after finishing sending the `pull` message

https://github.com/renproject/aw/blob/27ccfc3bf6e42e58328bafc71802d139da40f6a3/peer/gossip.go#L86-L87
This causes the incoming `sync` message will always be rejected.

**Comment by rahulghangas** [comment]
Fix pushed as part of [PR 56](https://github.com/renproject/aw/pull/56/commits/2ad3f2527aaf47a16db633cfe2c037bfce242292)

**Comment by jazg** [comment]
Just tested this out and it still seems to be causing problems. Is this conditional in the `DidReceiveMessage` method correct?

https://github.com/renproject/aw/blob/ac3835b6789ad7260e74dce6be88cf9bdedbb2db/peer/gossip.go#L70-L72

Based on the usage of `Filter` inside the syncer, I think it might need to be:

```go
if !g.filter.Filter(from, msg) { ... }
```

**Comment by rahulghangas** [comment]
I think the this is right, `Filter` should returns true if the content should be filtered, that is, should be blocked. However, the logic in `Filter` itself is slightly incorrect and should something like the following

```go
func (f *SyncFilter) Filter(from id.Signatory, msg wire.Msg) bool {
	if msg.Type != wire.MsgTypeSync {
		return true
	}

	f.expectingMu.RLock()
	defer f.expectingMu.RUnlock()

	expectedSyncs, ok := f.expecting[string(msg.Data)]
	if !ok {
		return true
	}
	return !(expectedSyncs > 0)
}
```

**Comment by jazg** [comment]
@rahulghangas That makes sense!

**Comment by rahulghangas** [comment]
@jazg I've pushed the changes with a basic test (it doesn't do anything, just shows that gossip works). Can you double-check on your end and subsequently close this issue if it's resolved

**Comment by jazg** [comment]
@rahulghangas Works on my end!
