### ISSUE TITLE
Receive functions not registered properly when having more than one receiver.

### ISSUE THREAD

**Issue by tok-kkk** [renproject/aw#60]
Inside the `channel` package, the `client.Receive()` function won't register receiver functions if you call it more than once. 
Calls after the first one will just exit and does nothing (since the `client.receiversRunning` has been marked to true)

I'm thinking to add 
```go
		select {
		case <-ctx.Done():
		case client.receivers <- receiver{ctx: ctx, f: f}:
		}
```	
between https://github.com/renproject/aw/blob/27ccfc3bf6e42e58328bafc71802d139da40f6a3/channel/client.go#L171-L172
but I realize it could cause a potential deadlock. 

I'll let you guys decide how to fix this.

**Comment by loongy** [comment]
The only reason this condition is here is to ensure that the Goroutine is only spawned once. So it should be fine to add the suggested select statement between L172 and L173. This avoids the deadlock issue.

**Comment by tok-kkk** [comment]
I think it will create a deadlock issue by adding the suggestion select statement.
Say the receive function has been called and the goroutine(let's call this goroutine1) has been running, and we try to call the receive function again(let's call this goroutine2). Goroutine2 will acquire the lock(L170) and wait until goroutine1 reads from the `client.receivers` channel, say unfortunately the ctx for previous receiver function expires and goroutine1 will break the loop and trying to acquire the lock(https://github.com/renproject/aw/blob/27ccfc3bf6e42e58328bafc71802d139da40f6a3/channel/client.go#L218-L225) and this will end up with a deadlock with each goroutine waiting for the other. 

Making the `receivers ` channel buffered would solve the deadlock issue but can introduce new issues. For example in the above scenario, it can end up with no goroutines handling messages.

**Comment by rahulghangas** [comment]
Fixed as part of [PR 56](https://github.com/renproject/aw/pull/56/commits/0e84c8562bb56b994d47c9c0348963b0c7fba1fe)

**Comment by jazg** [comment]
@rahulghangas Sweet! It would be good to have some regression tests for that if you haven't already added some.
