### ISSUE TITLE
Sync context always timing out

### ISSUE THREAD

**Issue by jazg** [renproject/aw#61]
There seem to be at least two issues in the syncer:

1. We're overriding the global context on the following lines, when instead we should probably be defining an inner context:

https://github.com/renproject/aw/blob/ac3835b6789ad7260e74dce6be88cf9bdedbb2db/peer/sync.go#L110-L117

2. The context always times out, even when the `DidReceiveMessage` function is called and the pending content flag is signalled. Is there a reason we can't have something as simple as the following?

```go
type pendingContent struct {
	// content is nil while synchronisation is happening. After synchronisation
	// has completed, content will be set.
	content chan []byte
}

func (pending *pendingContent) wait() <-chan []byte {
	return pending.content
}

func (pending *pendingContent) signal(content []byte) {
	pending.content <- content
}
```

**Comment by rahulghangas** [comment]
@jazg do you have an example demonstrating the problem? I understand this method needs some changes, but it would be great if I can see the exact problem first

**Comment by rahulghangas** [comment]
Nvm, reproduced it, will push fix

**Comment by rahulghangas** [comment]
Ok, this was a tricky one. Two issues, 
a) We never signaled the `cond`
b) The map we were using was keeping copies of the `pending` struct rather than a pointer

**Comment by jazg** [comment]
@rahulghangas Fix looks pretty good to me (although I still need to test it out)! I think the issue with the context still exists – I can push a quick fix for this though.
